#!/bin/bash

# Define the monitor name for xrandr
MONITOR_NAME="DisplayPort-0" # Adjust if needed

# Define the target resolution
TARGET_RESOLUTION="1720x1440"

# Get the current resolution of the monitor
CURRENT_RESOLUTION=$(xrandr | grep "$MONITOR_NAME connected" | grep -o -E "[0-9]+x[0-9]+\+[0-9]+\+[0-9]+" | cut -d '+' -f1)

# Check if the current resolution matches the target resolution
if [ "$CURRENT_RESOLUTION" = "$TARGET_RESOLUTION" ]; then
    # Run your script here
    sh ~/.screenlayout/pip_on.sh
    
fi

